/* GENERATED by scripts/gen_stub.py from depthai_c.h — do not edit.
 * Link-time stand-in used when DEPTHAI_SYS_SKIP_NATIVE=1: every call fails with
 * a clear error so `cargo check`/`cargo test` of pure-Rust code works on a
 * machine without depthai-core. Never ship a binary built this way. */
#include "depthai_c.h"

static const char* const STUB_MSG =
    "depthai-sys was built with DEPTHAI_SYS_SKIP_NATIVE=1 (no depthai-core linked)";

const char* dai_last_error(void) { return STUB_MSG; }
void dai_clear_last_error(void) {}
void dai_string_free(char* s) {}
const char* dai_build_version(void) { return "stub"; }
int dai_steady_clock_now_ns(int64_t* out) { return DAI_ERR; }
int dai_device_open(const char* name_or_id, int32_t max_usb_speed, dai_device** out) { return DAI_ERR; }
int dai_device_open_info(const dai_device_info* info, int32_t max_usb_speed, dai_device** out) { return DAI_ERR; }
void dai_device_release(dai_device* d) {}
int dai_device_close(dai_device* d) { return DAI_ERR; }
int dai_device_is_closed(const dai_device* d, int* out) { return DAI_ERR; }
int dai_device_id(dai_device* d, char** out) { return DAI_ERR; }
int dai_device_name(dai_device* d, char** out) { return DAI_ERR; }
int dai_device_usb_speed(dai_device* d, int32_t* out) { return DAI_ERR; }
int dai_device_platform(dai_device* d, int32_t* out) { return DAI_ERR; }
int dai_device_connected_cameras(dai_device* d, int32_t* sockets, size_t cap, size_t* n) { return DAI_ERR; }
int dai_device_connected_imu(dai_device* d, char** out) { return DAI_ERR; }
int dai_device_read_calibration(dai_device* d, dai_calib** out) { return DAI_ERR; }
int dai_device_set_ir_laser_dot_projector_intensity(dai_device* d, float intensity, int32_t mask, int* out_ok) { return DAI_ERR; }
int dai_device_set_ir_flood_light_intensity(dai_device* d, float intensity, int32_t mask, int* out_ok) { return DAI_ERR; }
int dai_device_all_available(dai_device_info* out, size_t cap, size_t* n) { return DAI_ERR; }
int dai_bootloader_open(const dai_device_info* info, dai_bootloader** out) { return DAI_ERR; }
void dai_bootloader_release(dai_bootloader* b) {}
int dai_pipeline_new(dai_device* device, dai_pipeline** out) { return DAI_ERR; }
int dai_pipeline_new_host_only(dai_pipeline** out) { return DAI_ERR; }
void dai_pipeline_release(dai_pipeline* p) {}
int dai_pipeline_build(dai_pipeline* p) { return DAI_ERR; }
int dai_pipeline_start(dai_pipeline* p) { return DAI_ERR; }
int dai_pipeline_stop(dai_pipeline* p) { return DAI_ERR; }
int dai_pipeline_wait(dai_pipeline* p) { return DAI_ERR; }
int dai_pipeline_is_running(const dai_pipeline* p, int* out) { return DAI_ERR; }
int dai_pipeline_is_built(const dai_pipeline* p, int* out) { return DAI_ERR; }
int dai_pipeline_remove(dai_pipeline* p, dai_node* n) { return DAI_ERR; }
int dai_pipeline_create_camera(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
int dai_pipeline_create_sync(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
int dai_pipeline_create_stereo_depth(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
int dai_pipeline_create_video_encoder(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
int dai_pipeline_create_imu(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
int dai_pipeline_create_gate(dai_pipeline* p, dai_node** out) { return DAI_ERR; }
void dai_node_release(dai_node* n) {}
int dai_node_id(const dai_node* n, int64_t* out) { return DAI_ERR; }
int dai_node_type_name(const dai_node* n, const char** out) { return DAI_ERR; }
int dai_node_output_ref(dai_node* n, const char* group, const char* name, dai_output** out) { return DAI_ERR; }
int dai_node_input_ref(dai_node* n, const char* group, const char* name, dai_input** out) { return DAI_ERR; }
int dai_node_output_names(dai_node* n, char** out) { return DAI_ERR; }
int dai_node_input_names(dai_node* n, char** out) { return DAI_ERR; }
int dai_output_name(dai_output* o, char** out) { return DAI_ERR; }
int dai_output_link(dai_output* o, dai_input* i) { return DAI_ERR; }
int dai_output_unlink(dai_output* o, dai_input* i) { return DAI_ERR; }
int dai_output_create_queue(dai_output* o, uint32_t max_size, int blocking, dai_queue** out) { return DAI_ERR; }
int dai_input_create_queue(dai_input* i, uint32_t max_size, int blocking, dai_input_queue** out) { return DAI_ERR; }
int dai_input_set_blocking(dai_input* i, int blocking) { return DAI_ERR; }
int dai_input_set_max_size(dai_input* i, uint32_t max_size) { return DAI_ERR; }
int dai_camera_build(dai_node* cam, int32_t socket, int32_t sensor_w, int32_t sensor_h, float sensor_fps) { return DAI_ERR; }
int dai_camera_board_socket(const dai_node* cam, int32_t* out) { return DAI_ERR; }
int dai_camera_request_output(dai_node* cam, uint32_t w, uint32_t h, int32_t type, int32_t resize_mode, float fps, int32_t undistort, dai_output** out) { return DAI_ERR; }
int dai_camera_request_full_resolution_output(dai_node* cam, int32_t type, float fps, int use_highest_resolution, dai_output** out) { return DAI_ERR; }
int dai_sync_input(dai_node* s, const char* key, dai_input** out) { return DAI_ERR; }
int dai_sync_set_sync_threshold_ns(dai_node* s, int64_t ns) { return DAI_ERR; }
int dai_sync_set_sync_attempts(dai_node* s, int32_t attempts) { return DAI_ERR; }
int dai_sync_set_run_on_host(dai_node* s, int run_on_host) { return DAI_ERR; }
int dai_stereo_depth_set_default_profile_preset(dai_node* s, int32_t preset) { return DAI_ERR; }
int dai_stereo_depth_set_left_right_check(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_set_subpixel(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_set_extended_disparity(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_set_output_size(dai_node* s, int32_t w, int32_t h) { return DAI_ERR; }
int dai_stereo_depth_set_depth_align_socket(dai_node* s, int32_t socket) { return DAI_ERR; }
int dai_stereo_depth_set_confidence_threshold(dai_node* s, int32_t threshold) { return DAI_ERR; }
int dai_stereo_depth_pp_set_spatial_filter_enable(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_pp_set_temporal_filter_enable(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_pp_set_speckle_filter_enable(dai_node* s, int enable) { return DAI_ERR; }
int dai_stereo_depth_pp_set_threshold_filter(dai_node* s, int32_t min_range, int32_t max_range) { return DAI_ERR; }
int dai_stereo_depth_pp_set_decimation_factor(dai_node* s, uint32_t factor) { return DAI_ERR; }
int dai_video_encoder_set_default_profile_preset(dai_node* e, float fps, int32_t profile) { return DAI_ERR; }
int dai_video_encoder_set_keyframe_frequency(dai_node* e, int32_t freq) { return DAI_ERR; }
int dai_video_encoder_set_bitrate_kbps(dai_node* e, int32_t kbps) { return DAI_ERR; }
int dai_video_encoder_set_bitrate(dai_node* e, int32_t bps) { return DAI_ERR; }
int dai_video_encoder_set_profile(dai_node* e, int32_t profile) { return DAI_ERR; }
int dai_video_encoder_set_rate_control_mode(dai_node* e, int32_t mode) { return DAI_ERR; }
int dai_video_encoder_set_num_bframes(dai_node* e, int32_t n) { return DAI_ERR; }
int dai_video_encoder_set_quality(dai_node* e, int32_t quality) { return DAI_ERR; }
int dai_video_encoder_set_lossless(dai_node* e, int lossless) { return DAI_ERR; }
int dai_gate_set_run_on_host(dai_node* g, int run_on_host) { return DAI_ERR; }
int dai_imu_enable_sensor(dai_node* imu, int32_t sensor, uint32_t report_rate_hz) { return DAI_ERR; }
int dai_imu_set_batch_report_threshold(dai_node* imu, int32_t n) { return DAI_ERR; }
int dai_imu_set_max_batch_reports(dai_node* imu, int32_t n) { return DAI_ERR; }
void dai_queue_release(dai_queue* q) {}
int dai_queue_try_get(dai_queue* q, dai_msg** out) { return DAI_ERR; }
int dai_queue_get(dai_queue* q, int64_t timeout_ns, dai_msg** out) { return DAI_ERR; }
int dai_queue_has(dai_queue* q, int* out) { return DAI_ERR; }
int dai_queue_size(dai_queue* q, uint32_t* out) { return DAI_ERR; }
int dai_queue_close(dai_queue* q) { return DAI_ERR; }
int dai_queue_is_closed(dai_queue* q, int* out) { return DAI_ERR; }
int dai_queue_set_blocking(dai_queue* q, int blocking) { return DAI_ERR; }
int dai_queue_set_max_size(dai_queue* q, uint32_t max_size) { return DAI_ERR; }
int dai_queue_name(dai_queue* q, char** out) { return DAI_ERR; }
void dai_input_queue_release(dai_input_queue* q) {}
int dai_input_queue_send(dai_input_queue* q, const dai_msg* m) { return DAI_ERR; }
void dai_msg_release(dai_msg* m) {}
int dai_msg_clone(const dai_msg* m, dai_msg** out) { return DAI_ERR; }
int dai_msg_datatype(const dai_msg* m, int32_t* out) { return DAI_ERR; }
int dai_buffer_get_info(const dai_msg* m, dai_buffer_info* out) { return DAI_ERR; }
int dai_msg_data(const dai_msg* m, const uint8_t** ptr, size_t* len) { return DAI_ERR; }
int dai_msg_timestamp_ns(const dai_msg* m, int64_t* out) { return DAI_ERR; }
int dai_msg_timestamp_device_ns(const dai_msg* m, int64_t* out) { return DAI_ERR; }
int dai_msg_sequence_num(const dai_msg* m, int64_t* out) { return DAI_ERR; }
int dai_img_frame_get_info(const dai_msg* m, dai_img_frame_info* out) { return DAI_ERR; }
int dai_img_frame_plane_stride(const dai_msg* m, int32_t plane, uint32_t* out) { return DAI_ERR; }
int dai_img_frame_plane_height(const dai_msg* m, uint32_t* out) { return DAI_ERR; }
int dai_encoded_frame_get_info(const dai_msg* m, dai_encoded_frame_info* out) { return DAI_ERR; }
int dai_imu_data_packets(const dai_msg* m, dai_imu_packet* out, size_t cap, size_t* n) { return DAI_ERR; }
int dai_gate_control_new(int open, int32_t num_messages, int32_t fps, dai_msg** out) { return DAI_ERR; }
int dai_msg_group_get(const dai_msg* g, const char* name, dai_msg** out) { return DAI_ERR; }
int dai_msg_group_num_messages(const dai_msg* g, int64_t* out) { return DAI_ERR; }
int dai_msg_group_names(const dai_msg* g, char** out) { return DAI_ERR; }
int dai_msg_group_is_synced(const dai_msg* g, int64_t threshold_ns, int* out) { return DAI_ERR; }
int dai_msg_group_interval_ns(const dai_msg* g, int64_t* out) { return DAI_ERR; }
void dai_calib_release(dai_calib* c) {}
int dai_calib_camera_intrinsics(const dai_calib* c, int32_t socket, int32_t w, int32_t h, float out_k[9]) { return DAI_ERR; }
int dai_calib_distortion_coefficients(const dai_calib* c, int32_t socket, float* out, size_t cap, size_t* n) { return DAI_ERR; }
int dai_calib_distortion_model(const dai_calib* c, int32_t socket, int32_t* out) { return DAI_ERR; }
int dai_calib_camera_extrinsics(const dai_calib* c, int32_t src, int32_t dst, int use_spec_translation, int32_t unit, float out_t[16]) { return DAI_ERR; }
int dai_calib_imu_to_camera_extrinsics(const dai_calib* c, int32_t socket, int use_spec_translation, int32_t unit, float out_t[16]) { return DAI_ERR; }
int dai_calib_camera_to_imu_extrinsics(const dai_calib* c, int32_t socket, int use_spec_translation, int32_t unit, float out_t[16]) { return DAI_ERR; }
int dai_calib_baseline_distance(const dai_calib* c, int32_t cam1, int32_t cam2, int use_spec_translation, int32_t unit, float* out) { return DAI_ERR; }
int dai_calib_stereo_left_socket(const dai_calib* c, int32_t* out) { return DAI_ERR; }
int dai_calib_stereo_right_socket(const dai_calib* c, int32_t* out) { return DAI_ERR; }
int dai_calib_fov(const dai_calib* c, int32_t socket, int use_spec, float* out) { return DAI_ERR; }
