#!/usr/bin/env python3
"""Regenerate csrc/depthai_c_stub.c from csrc/depthai_c.h (run after editing the header)."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent / "csrc"
src = re.sub(r"/\*.*?\*/", "", (root / "depthai_c.h").read_text(), flags=re.S)
decls = re.findall(r"^\s*((?:const char\*|int|void)\s+dai_\w+\s*\([^;]*?\))\s*;", src, flags=re.M | re.S)
out = [
    "/* GENERATED by scripts/gen_stub.py from depthai_c.h — do not edit.",
    " * Link-time stand-in used when DEPTHAI_SYS_SKIP_NATIVE=1: every call fails with",
    " * a clear error so `cargo check`/`cargo test` of pure-Rust code works on a",
    " * machine without depthai-core. Never ship a binary built this way. */",
    '#include "depthai_c.h"',
    "",
    "static const char* const STUB_MSG =",
    '    "depthai-sys was built with DEPTHAI_SYS_SKIP_NATIVE=1 (no depthai-core linked)";',
    "",
]
for d in decls:
    d = re.sub(r"\s+", " ", d).strip()
    name = re.search(r"(dai_\w+)\s*\(", d).group(1)
    ret = d.split(name)[0].strip()
    if name == "dai_last_error":
        body = "{ return STUB_MSG; }"
    elif name == "dai_build_version":
        body = '{ return "stub"; }'
    elif ret == "void":
        body = "{}"
    else:
        body = "{ return DAI_ERR; }"
    out.append(f"{d} {body}")
(root / "depthai_c_stub.c").write_text("\n".join(out) + "\n")
print(f"wrote {len(decls)} stubs")
