#!/usr/bin/env python3
"""Regenerate src/ffi.rs (the `extern "C"` block) from csrc/depthai_c.h.

Run after editing the header. Structs, enum constants and tests live in
src/lib.rs by hand; only the function declarations are generated.
"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = re.sub(r"/\*.*?\*/", "", (root / "csrc" / "depthai_c.h").read_text(), flags=re.S)
decls = re.findall(r"^\s*((?:const char\*|int|void)\s+dai_\w+\s*\([^;]*?\))\s*;", src, flags=re.M | re.S)

HANDLES = ["dai_device", "dai_pipeline", "dai_node", "dai_output", "dai_input", "dai_queue", "dai_input_queue",
           "dai_msg", "dai_calib", "dai_bootloader", "dai_nn_archive"]
PODS = ["dai_device_info", "dai_buffer_info", "dai_img_frame_info", "dai_imu_vec_report", "dai_imu_rotvec_report",
        "dai_imu_packet", "dai_encoded_frame_info", "dai_nn_model_description", "dai_tensor_info",
        "dai_img_detection"]

def map_type(t: str) -> str:
    t = re.sub(r"\s+", " ", t).strip()
    # array params decay to pointers
    scalar = {"int": "c_int", "int32_t": "i32", "uint32_t": "u32", "int64_t": "i64",
              "size_t": "usize", "float": "f32", "uint8_t": "u8", "char": "c_char"}
    m = re.fullmatch(r"(const )?(\w+)( ?\*)*", t)
    if not m:
        raise SystemExit(f"cannot map type: {t!r}")
    const = bool(m.group(1))
    base = m.group(2)
    stars = t.count("*")
    if base in HANDLES or base in PODS:
        rust_base = base
    else:
        rust_base = scalar[base]
    if stars == 0:
        return rust_base
    # innermost pointer carries the const-ness of the base; outer pointers are *mut
    out = f"*const {rust_base}" if const else f"*mut {rust_base}"
    for _ in range(stars - 1):
        out = f"*mut {out}"
    return out

lines = ["//! GENERATED by scripts/gen_ffi.py from csrc/depthai_c.h — do not edit by hand.",
         "//! One `extern \"C\"` declaration per shim function, in header order.",
         "",
         "use std::os::raw::{c_char, c_int};",
         "",
         "use crate::{dai_bootloader, dai_buffer_info, dai_calib, dai_device, dai_device_info,",
         "            dai_encoded_frame_info, dai_img_frame_info, dai_imu_packet, dai_input, dai_input_queue,",
         "            dai_img_detection, dai_msg, dai_nn_archive, dai_nn_model_description, dai_tensor_info,",
         "            dai_node, dai_output, dai_pipeline, dai_queue};",
         "",
         "extern \"C\" {"]
for d in decls:
    d = re.sub(r"\s+", " ", d).strip()
    m = re.match(r"(const char\*|int|void)\s+(dai_\w+)\s*\((.*)\)$", d)
    ret, name, params = m.group(1), m.group(2), m.group(3).strip()
    rust_params = []
    if params and params != "void":
        for p in params.split(","):
            p = p.strip()
            # split type / name ; handle `float out_k[9]`
            pm = re.match(r"(.+?)\s*(\w+)(\[\d+\])?$", p)
            ptype, pname, arr = pm.group(1).strip(), pm.group(2), pm.group(3)
            if arr:
                ptype = ptype + "*"
            if pname in ("type", "mod", "ref", "in", "self"):
                pname += "_"
            rust_params.append(f"{pname}: {map_type(ptype)}")
    rust_ret = {"int": " -> c_int", "void": "", "const char*": " -> *const c_char"}[ret]
    lines.append(f"    pub fn {name}({', '.join(rust_params)}){rust_ret};")
lines.append("}")
out = root / "src" / "ffi.rs"
out.write_text("\n".join(lines) + "\n")
import shutil, subprocess
if shutil.which("rustfmt"):
    subprocess.run(["rustfmt", "--edition", "2021", "--config", "max_width=100", str(out)], check=True)
print(f"wrote {len(decls)} declarations")
